### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by SamuelBrucksch** [raul-ortega/amv-open360tracker-32bits#1]
Hi Raul,

good work on porting this project to naze32. Can you please upload the source code as well?

Cheers

Samuel

**Comment by raul-ortega** [comment]
Hi Samuel, I apologize for not responding sooner. 

I will publish the code, but not now, because I have still a lot of pending work with this firmware, and I'm not much proud about the coding style, and I have to refactor and clean many things. The purpose of the repository by now will be to provide a place from where my comunity users, wich are testing all the progress I make, can download the hex file. But of course, I'll publish it here.

Many of the functionalities are completely experimental and I'm continuoslly making lots of changes. In this moment I'm working in a menu of configuration options, by using the calibraiton and home buttons and the OLED display, the users will be able to change from one protocol to another (and other parameter) without needing to compile the code and upload to the controller (we normally go to the field with more than one drone which have different flight controllers and use different telemetry protocols).

This is one of the main goals of porting the firmware to STM32 based controllers, and of course, other many advantages as you can imagine. I did a first try with the Arduino based controllers, but I was having a lot of issues: memory size, crashes, ...

I thought why not to reuse the source code of one of the most popular flight controller boards in the DIY world? What I've done is mixing the the source code of the 8bit version with cleanflight,  so most of the work of coding drivers for peripherials are done, and at the same time the firmware could be compiled for the supported flight controllers with builtin magnetometer (and external ones, I gues...).

With this scenario we are able to manage until 4 serial ports (2 uarts and 2 sofserial ports), so we can use one of them to convert/forward the telemetry data. I've added, and tested with success, the functionality of conversion of input telemetry data to mavlink packets (only gps coordinates and altitude), and forwarded through bluetooth module to the Droidplaner app: https://www.youtube.com/watch?v=bq1js9k7rgU

I've started this new proyect with quite good results, this week, one of my friends has made the first real flight with this version of the firmware (the magenetometer offset  has already been solved).

https://www.youtube.com/watch?v=KPuANginQxc

A lot of ideas, a lot of work... but we are in the good way...
