### ISSUE TITLE
Servo reverse

### ISSUE THREAD

**Issue by CountZ74** [raul-ortega/amv-open360tracker-32bits#4]
Could you include a servo reverse setting? It would be great to support other hardware.

Thanks,

Sebastian

**Comment by SamuelBrucksch** [comment]
For tilt you just need to exchangeTILT_0 and TILT_90. On PAN its not possible right now i think.

**Comment by CountZ74** [comment]
Thank you for your answer. Since Raul is using baseflight for his tracker firmware and baseflight has a servo reverse feature for planes, it should be no problem for him to include it. He also should provide the sources, baseflight is GPL licensed and everything that uses it, is too.

**Comment by MarenB** [comment]
+1 
I would like that feature, too.
And further more, a compas inverting function would be great, as well. If a user (like me) wants to use GPS with integrated compass, the heading would me measured wrong, because in most of these modules, the compass is mounted upside down on the bottom of the PCB.

**Comment by raul-ortega** [comment]
This issue has been solved at https://github.com/raul-ortega/u360gts repository (only source code, hex version 7.0 not yet uploaded).
Please could you move this issue to there? This repository will be removed soon. Thanks.
